### PR TITLE
feat: make ID optional 

### PR DESCRIPTION
**Pull request by DCKT**
Hi !

I finally moved on and successfully did it from https://github.com/cknitt/bs-react-intl-extractor/pull/69

What do you think about this change ?

### CODE REVIEW

**Comment by cknitt** [comment]
Hi @DCKT, thanks a lot for your PR. I will look into it over the weekend.

**Comment by DCKT** [comment]
Thanks for you answer, I tried to use it on my side and I have a compilation error about missing `id` field in the record.
I don't understand where the type association come from ATM

**Comment by DCKT** [comment]
A little update, my implementation is dumb, it's generate the `id` in the extract but he's missing in the application, that was the purpose of my [first PR](https://github.com/cknitt/bs-react-intl-extractor/pull/69), the `@intl.messages` would be used as a ppx in order to generate the ID in the app too.

**Comment by cknitt** [comment]
Hi @DCKT, I finally found time to look into your PR.

I see some problems with this approach:

1. According to the react-intl docs, the message id should be "a unique, stable identifier for the message". If we generate the id as proposed, it will be (somewhat) unique, but not stable - if you make any change to the default message text (e.g. "User name" -> "Username"), the message id will also change. Maybe that is intentional in your workflow, but it is not something I would want. In my workflow, I would use something like "Login.username" for the id.
2. The extractor is intentionally designed as a standalone tool and not a PPX. However, like you wrote, we would need a PPX that adds the generated id to the AST for this approach to work (for both FormattedMessage elements and objects with a `defaultMessage` field within a module with the `@@intl.messages` attribute). This is not something I see in the scope of this project or would like to maintain.

**Comment by DCKT** [comment]
Hello !

Thanks for looking, I understand your points (this looks like not very funny to maintain 😄 )
If you or somebody want to try this feature in a project here's how : 
```
yarn add @colisweb/bs-react-intl-extractor-bin res-react-intl
```

Add the ppx in `bsconfig.json`
```
"ppx-flags": ["res-react-intl/ppx"],
```

To extract make sure to use the `bs-react-intl-extractor` bin exposed from `@colisweb/bs-react-intl-extractor-bin`

Have a great day !

**Pull request closed without merging**
